<a href="https://colab.research.google.com/github/PaulToronto/University-of-Colorado-Boulder---Essential-Math-Specialization/blob/main/2_2_Matrix_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 2.2 Matrix Algebra

## Imports

In [1]:
import numpy as np
import sympy as sym

## 2.2.1 Introduction to Matrix Algebra + Sum + Scale

### 2.2.1.1 Matrix Algebra Sum

Let $A$ and $B$ be two matrices.

- We can only find the sum of $A$ and $B$ of they have the same dimensions
- To perform the addition simply add the corresponding elements

$$
A = \begin{bmatrix}
1 & 2 \\
-1 & 0 \\
1 & 7
\end{bmatrix},
B = \begin{bmatrix}
7 & -2 \\
6 & -6 \\
5 & -2
\end{bmatrix}
$$

$$
A + B = \begin{bmatrix}
8 & 0 \\
5 & -6 \\
6 & 5
\end{bmatrix}
$$

#### Matrix Addition with `numpy`

In [2]:
A = np.array([[1, 2],
              [-1, 0],
              [1, 7]])

B = np.array([[7, -2],
              [6, -6],
              [5, -2]])

A + B

array([[ 8,  0],
       [ 5, -6],
       [ 6,  5]])

#### Matrix Addition with `sympy`

In [3]:
A = sym.Matrix(A)
B = sym.Matrix(B)

A + B

Matrix([
[8,  0],
[5, -6],
[6,  5]])

### 2.2.1.2 Matrix Algebra Scale + Identity

#### Scale

To multiply a matrix by a scalar, simply multiple each element by the scalar.

Let

$$
A = \begin{bmatrix}
-1 & 1 \\
7 & \sqrt{3}
\end{bmatrix}
$$

$$
2A = \begin{bmatrix}
-2 & 2 \\
14 & 2\sqrt{3}
\end{bmatrix}
$$

#### Scalar Multiplication with `numpy`

In [4]:
A = np.array([[-1, 1],
              [7, np.sqrt(3)]])

2 * A

array([[-2.        ,  2.        ],
       [14.        ,  3.46410162]])

#### Scalar Multiplication with `sympy`

In [5]:
A = sym.Matrix([[-1, 1],
                [7, sym.sqrt(3)]])
A

Matrix([
[-1,       1],
[ 7, sqrt(3)]])

In [6]:
2 * A

Matrix([
[-2,         2],
[14, 2*sqrt(3)]])

#### Identity

Let $I$ be an $n \times n$ identity matrix.

$$
AI = A = IA
$$

## 2.2.2 Matrix Multiplication

### 2.2.2.1 Matrix Multiplication + Small Example


In [7]:
a, b, c, d = sym.symbols('a b c d')
e, f, g, h = sym.symbols('e f g h')

A = sym.Matrix([[a, b],
                [c, d]])
B = sym.Matrix([[e, f],
                [g, h]])

In [8]:
A @ B

Matrix([
[a*e + b*g, a*f + b*h],
[c*e + d*g, c*f + d*h]])

In [9]:
sym.Matrix([[A.row(0) @ B.col(0), A.row(0) @ B.col(1)],
            [A.row(1) @ B.col(0), A.row(1) @ B.col(1)]])

Matrix([
[a*e + b*g, a*f + b*h],
[c*e + d*g, c*f + d*h]])

### Example

Let $A = \begin{bmatrix}1 & 2\\-1 & -1\end{bmatrix}$ and $B = \begin{bmatrix}3 & -1\\1 & 4\end{bmatrix}$.

$$
\begin{align}
AB &= \begin{bmatrix}1 & 2\\-1 & -1\end{bmatrix}\cdot\begin{bmatrix}3 & -1\\1 & 4\end{bmatrix} \\
&= \begin{bmatrix}(1)(3) + (2)(1) & (1)(-1) + (2)(4)\\
(-1)(3) + (-1)(1) & (-1)(-1) + (-1)(4) \\
\end{bmatrix} \\
&= \begin{bmatrix}5 & 7\\-4 & -3\end{bmatrix}
\end{align}
$$

### Matrix Multipliation with `numpy`

In [10]:
A = np.array([[1, 2],
               [-1, -1]])

B = np.array([[3, -1],
               [1, 4]])


In [11]:
A @ B

array([[ 5,  7],
       [-4, -3]])

In [12]:
A * B # wrong, this is element-wise

array([[ 3, -2],
       [-1, -4]])

In [13]:
np.matmul(A, B)

array([[ 5,  7],
       [-4, -3]])

### Matrix Multiplication with `sympy`

In [14]:
A = sym.Matrix(A)
B = sym.Matrix(B)

In [15]:
A @ B

Matrix([
[ 5,  7],
[-4, -3]])

In [16]:
A * B

Matrix([
[ 5,  7],
[-4, -3]])

### 2.2.2.2 Matrix Multiplication - General Rules

Let $A_{m,n}$ and $B_{q,p}$ be matrices.

- We can only multiply these two matrices together if $n = q$.
- The resulting matrix will be an $m \times p$ matrix.


In [17]:
A = np.array([[1, 2],
              [-1, 3],
              [4, 1]])

B = np.array([[1, -1],
              [2, 3]])

In [18]:
A.shape, B.shape

((3, 2), (2, 2))

These two matrices can be multiplied and the result will be a $3 \times 2$ matrix.

### 2.2.2.3 Matrix Multiplication Example

Find $A \cdot B$
$$
A = \left[\begin{matrix}1 & 2\\-1 & 3\\4 & 1\end{matrix}\right], B = \left[\begin{matrix}1 & -1\\2 & 3\end{matrix}\right]
$$

In [19]:
A @ B

array([[ 5,  5],
       [ 5, 10],
       [ 6, -1]])

In [20]:
A = sym.Matrix(A)
B = sym.Matrix(B)

In [21]:
A @ B

Matrix([
[5,  5],
[5, 10],
[6, -1]])

In [22]:
sym.Matrix([[A.row(0) @ B.col(0), A.row(0) @ B.col(1)],
            [A.row(1) @ B.col(0), A.row(1) @ B.col(1)],
            [A.row(2) @ B.col(0), A.row(2) @ B.col(1)]])

Matrix([
[5,  5],
[5, 10],
[6, -1]])

### 2.2.2.4 Identity Matrix + Example

- $I_n$ is the **identity matrix**.
- An identity matrix must be a square matrix.
- An identity matrix consists of 0s, except for the diagonal, which are 1s.

$$
I_n \cdot A = A \cdot I_m = A
$$

#### Example

$$
I_3 \cdot A_{3\times2} = A_{3\times2} \cdot I_2 = A_{3\times2}
$$

In [23]:
a11, a12 = sym.symbols('a_{11} a_{12}')
a21, a22 = sym.symbols('a_{21} a_{22}')
a31, a32 = sym.symbols('a_{31} a_{32}')

A = sym.Matrix([[a11, a12],
                [a21, a22],
                [a31, a32]])
A

Matrix([
[a_{11}, a_{12}],
[a_{21}, a_{22}],
[a_{31}, a_{32}]])

In [24]:
I3 = sym.eye(3)
I3

Matrix([
[1, 0, 0],
[0, 1, 0],
[0, 0, 1]])

In [25]:
I2 = sym.eye(2)
I2

Matrix([
[1, 0],
[0, 1]])

In [26]:
I3 @ A

Matrix([
[a_{11}, a_{12}],
[a_{21}, a_{22}],
[a_{31}, a_{32}]])

In [27]:
A @ I2

Matrix([
[a_{11}, a_{12}],
[a_{21}, a_{22}],
[a_{31}, a_{32}]])