<a href="https://colab.research.google.com/github/PaulToronto/University-of-Colorado-Boulder---Essential-Math-Specialization/blob/main/2_4_Determinants_and_Eigens.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 2.4 Determinants and Eigens

## Imports

In [23]:
import sympy as sym
import numpy as np

## 2.4.1 Determinants

### 2.4.1.1 Determinants Intro and $2 \times 2$ Example

In [24]:
a, b, c, d = sym.symbols('a b c d')
M = sym.Matrix([[a, b],
                [c, d]])
M

Matrix([
[a, b],
[c, d]])

In [25]:
M.det()

a*d - b*c

#### Example

In [26]:
M = np.array([[1, 3],
              [-2, 4]])
M

array([[ 1,  3],
       [-2,  4]])

In [27]:
1 * 4 - 3 * (-2)

10

In [28]:
np.linalg.det(M)

9.999999999999998

In [29]:
M = sym.Matrix(M)
M

Matrix([
[ 1, 3],
[-2, 4]])

In [30]:
M.det()

10

### 2.4.1.2 Inverse of $2 \times 2$ Matrix - Quick Method

$$
A = \begin{bmatrix}a&b\\c&d\end{bmatrix}
$$

$$
\det{(A)} = \left|A\right| = ad - bc
$$

$$
A^{-1} = \frac{1}{\left|A\right|}\begin{bmatrix}d&-b\\-c&a\end{bmatrix}
$$

Note that $A^{-1}$ exists if and only if the matrix is **non-singular**, which means that its determinant is non-zero.

#### Example

$$
B = \begin{bmatrix}1&3\\-2&-4\end{bmatrix}
$$

Find $B^{-1}$

In [31]:
B = np.array([[1, 3],
             [-2, -4]])

B

array([[ 1,  3],
       [-2, -4]])

In [32]:
det_B = B[0, 0] * B[1, 1] - B[0, 1] * B[1, 0]
det_B, np.linalg.det(B)

(2, 2.0)

In [33]:
B_inv = (1/det_B) * np.array([[-4, -3],
                          [2, 1]])
B_inv

array([[-2. , -1.5],
       [ 1. ,  0.5]])

In [34]:
np.linalg.inv(B)

array([[-2. , -1.5],
       [ 1. ,  0.5]])

In [35]:
B = sym.Matrix(B)
B

Matrix([
[ 1,  3],
[-2, -4]])

In [36]:
B.det()

2

In [37]:
B.inv()

Matrix([
[-2, -3/2],
[ 1,  1/2]])

### 2.4.1.3 Determinant of a $3 \times 3$ Matrix - Overview