<a href="https://colab.research.google.com/github/PaulToronto/University-of-Colorado-Boulder---Essential-Math-Specialization/blob/main/2_4_Determinants_and_Eigens.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 2.4 Determinants and Eigens

## Imports

In [1]:
import sympy as sym
import numpy as np

## 2.4.1 Determinants

### 2.4.1.1 Determinants Intro and $2 \times 2$ Example

In [2]:
a, b, c, d = sym.symbols('a b c d')
M = sym.Matrix([[a, b],
                [c, d]])
M

Matrix([
[a, b],
[c, d]])

In [3]:
M.det()

a*d - b*c

#### Example

In [4]:
M = np.array([[1, 3],
              [-2, 4]])
M

array([[ 1,  3],
       [-2,  4]])

In [5]:
1 * 4 - 3 * (-2)

10

In [6]:
np.linalg.det(M)

9.999999999999998

In [7]:
M = sym.Matrix(M)
M

Matrix([
[ 1, 3],
[-2, 4]])

In [8]:
M.det()

10

### 2.4.1.2 Inverse of $2 \times 2$ Matrix - Quick Method

$$
A = \begin{bmatrix}a&b\\c&d\end{bmatrix}
$$

$$
\det{(A)} = \left|A\right| = ad - bc
$$

$$
A^{-1} = \frac{1}{\left|A\right|}\begin{bmatrix}d&-b\\-c&a\end{bmatrix}
$$

Note that $A^{-1}$ exists if and only if the matrix is **non-singular**, which means that its determinant is non-zero.

#### Example

$$
B = \begin{bmatrix}1&3\\-2&-4\end{bmatrix}
$$

Find $B^{-1}$

In [9]:
B = np.array([[1, 3],
             [-2, -4]])

B

array([[ 1,  3],
       [-2, -4]])

In [10]:
det_B = B[0, 0] * B[1, 1] - B[0, 1] * B[1, 0]
det_B, np.linalg.det(B)

(2, 2.0)

In [11]:
B_inv = (1/det_B) * np.array([[-4, -3],
                          [2, 1]])
B_inv

array([[-2. , -1.5],
       [ 1. ,  0.5]])

In [12]:
np.linalg.inv(B)

array([[-2. , -1.5],
       [ 1. ,  0.5]])

In [13]:
B = sym.Matrix(B)
B

Matrix([
[ 1,  3],
[-2, -4]])

In [14]:
B.det()

2

In [15]:
B.inv()

Matrix([
[-2, -3/2],
[ 1,  1/2]])

### 3Blue1Brown

<img src='https://drive.google.com/uc?export=view&id=1iyiapt1QxNhRA2dtNCSQTWAMNzPp5kwF'>

The determinant is the area of the parallelogram.

$$
\begin{align}
Area &= (a + b)(c + d) - ac - bd - 2bc \\
&= ac + ad + bc + bd - ac - bd - 2bc \\
&= ad - bc
\end{align}
$$

### 2.4.1.3 Determinant of a $3 \times 3$ Matrix - Overview

$$
A = \begin{bmatrix}
a&b&c\\d&e&f\\g&h&i
\end{bmatrix}
$$
<hr>
Alternate signs no matter which row is chosen to start:
$$
\begin{bmatrix}
+&-&+\\-&+&-\\+&-&+
\end{bmatrix}
$$
<hr>

Choosing the first row:
$$
\begin{align}
\det{(A)} &= \left|A\right| \\
&=
a\begin{vmatrix}e&f\\h&i\end{vmatrix}\
- b\begin{vmatrix}d&f\\g&i\end{vmatrix}
+ c\begin{vmatrix}d&e\\g&h\end{vmatrix}
\end{align}
$$

### 2.4.1.4 Determinant of a $3 \times 3$ Matrix - Example with 1st Row

In [16]:
M = sym.Matrix([[1, 5, 0],
                [2, 4, -1],
                [0, -2, 0]])
M

Matrix([
[1,  5,  0],
[2,  4, -1],
[0, -2,  0]])

$$
\begin{align}
\left|M\right| &=
\begin{vmatrix}4&-1\\-2&0\end{vmatrix}
- 5\begin{vmatrix}2&-1\\0&0\end{vmatrix}
+ 0\begin{vmatrix}2&4\\0&-2\end{vmatrix} \\
&= - 2 - 5(0) + 0(-4) \\
&= -2
\end{align}
$$

In [17]:
M.det()

-2

### 2.4.1.5 Determinant of a $3 \times 3$ Matrix - Example with 2nd Row

$$
\begin{align}
\left|M\right| &=
-2\begin{vmatrix}5&0\\-2&0\end{vmatrix}
+4\begin{vmatrix}1&0\\0&0\end{vmatrix}
+\begin{vmatrix}1&5\\0&-2\end{vmatrix} \\
&= (-2)(0) + 4(0) + (-2 - 0) \\
&= -2
\end{align}
$$

## 2.4.2 Eigenvalues and Eigenvectors

### 2.4.2.1 Eigenvalue and Eigenvector - Overview

Let $\mathbf{A}$ be an $n \times n$ matrix.

- A non-zero vector $\mathbf{x}$ is called an **eigenvector** of $\mathbf{A}$ if and only if there is a scalar $\lambda$ such that $\mathbf{A}\mathbf{x} = \lambda\mathbf{x}$.
    - What this says is that the image of $\mathbf{x}$ is a scalar multiple of $\mathbf{x}$
- An **eigenvalue** is a scalar $\lambda$ such that $A\mathbf{x} = \lambda\mathbf{x}$, for some non-zero vector $\mathbf{x}$.

$$
\mathbf{A} = \begin{bmatrix}1&6\\5&2\end{bmatrix}, \mathbf{u} = \begin{bmatrix}6\\-5\end{bmatrix}, \mathbf{v} = \begin{bmatrix}3\\-2\end{bmatrix}
$$

In [18]:
A = sym.Matrix([[1, 6],
                [5, 2]])
u = sym.Matrix([6, -5])
v = sym.Matrix([3, -2])

Is $\mathbf{u}$ an eigenvector of $\mathbf{A}$?

$$
\begin{align}
\mathbf{A}\mathbf{u} &= \begin{bmatrix}1&6\\5&2\end{bmatrix}
\begin{bmatrix}6\\-5\end{bmatrix} \\
&= \begin{bmatrix}-24\\20\end{bmatrix} \\
&= -4\begin{bmatrix}6\\-5\end{bmatrix}
\end{align}
$$

$\therefore \mathbf{u}$ is an eigenvector of $\mathbf{A}$ and its associated eigenvalue is -4.

In [19]:
A @ u == -4 * u

True

Is $\mathbf{v}$ and eigenvector of $\mathbf{A}$?

$$
\begin{align}
\mathbf{A}\mathbf{v} &= \begin{bmatrix}1&6\\5&2\end{bmatrix}
\begin{bmatrix}3\\-2\end{bmatrix} \\
&= \begin{bmatrix}-9\\11\end{bmatrix} \\
&= \lambda\begin{bmatrix}3\\-2\end{bmatrix} \\
\end{align}
$$

There is no $\lambda$ that satisfies the equation.

$\therefore \mathbf{v}$ is not an eigenvector of $\mathbf{A}$

In [20]:
A @ v

Matrix([
[-9],
[11]])

### 2.4.2.2 Finding Eigenvector if Given Eigenvalue

$$
\mathbf{A} = \begin{bmatrix}1&6\\5&2\end{bmatrix}
$$

We know that $\lambda = 7$ is an eigenvalue of $\mathbf{A}$. Find an associated eigenvector.

$$
\begin{align}
&\mathbf{A}\mathbf{x} = \lambda\mathbf{x} \\
&\implies
\mathbf{A}\mathbf{x} - \lambda\mathbf{x} = \mathbf{0} \\
&\implies \left(\mathbf{A} - \lambda\mathbf{I}\right)\mathbf{x} = \mathbf{0}
\end{align}
$$
<br>
$$
\begin{align}
&\left(
    \begin{bmatrix}1&6\\5&2\end{bmatrix}
    - 7 \begin{bmatrix}1&0\\0&1\end{bmatrix}
\right)\mathbf{x} = \mathbf{0} \\
&\implies
\begin{bmatrix}-6&6\\5&-5\end{bmatrix}\mathbf{x} = \mathbf{0} \\
&\implies
\begin{bmatrix}-6&6&0\\5&-5&0\end{bmatrix}
\end{align}
$$

We now have an augmented matrix. Let's call it $\mathbf{M}$.

In [21]:
M = sym.Matrix([[-6, 6, 0],
                [5, -5, 0]])
M.rref(pivots=False)

Matrix([
[1, -1, 0],
[0,  0, 0]])

The eigenvector is any vector where $x_1 = x_2$, choosing the simplest one we have eigenvector:

$$
\mathbf{x} = \begin{bmatrix}1\\1\end{bmatrix}
$$

Verify our result:

$$
\begin{align}
\mathbf{A}\mathbf{x} &= 7\mathbf{x}  \\
\begin{bmatrix}1&6\\5&2\end{bmatrix}
\begin{bmatrix}1\\1\end{bmatrix} &= 7\begin{bmatrix}1\\1\end{bmatrix} \\
\begin{bmatrix}1+6\\5+2\end{bmatrix} &= \begin{bmatrix}7\\7\end{bmatrix} \\
\begin{bmatrix}7\\7\end{bmatrix} &= \begin{bmatrix}7\\7\end{bmatrix}
\end{align}
$$

### 2.4.2.3 Characteristic Polynomial - Finding Eigenvalues

#### First a Review

$$
\begin{align}
\mathbf{M}\mathbf{x} &= \mathbf{0}\\
\mathbf{M^{-1}}\mathbf{M}\mathbf{x} &= \mathbf{M^{-1}}\mathbf{0}\\
\mathbf{I}\mathbf{x} &= \mathbf{M^{-1}}\mathbf{0} \\
\mathbf{x} &= \mathbf{M^{-1}}\mathbf{0}
\end{align}
$$

If $\mathbf{M}$ is invertible, then $\mathbf{x} = \begin{bmatrix}0\\0\end{bmatrix}$, but an eigenvector can't be the zero vector.

In order for there to be a non-trivial solution, $\mathbf{M}$ can't be invertible, that is $\det{(\mathbf{M})} = 0$

<hr>

#### Finding Eigenvalues

Find the eigenvalues of $\mathbf{A}$

$$
\mathbf{A} = \begin{bmatrix}2&3\\3&-6\end{bmatrix}
$$

Solution:

Let $\mathbf{x}$ be an eigenvector of $\mathbf{A}$.

$$
\begin{align}
\mathbf{A}\mathbf{x} = \lambda\mathbf{x} \\
\left(\mathbf{A} - \lambda\mathbf{I}\right)\mathbf{x} &= \mathbf{0}\\
\left(\begin{bmatrix}2&3\\3&-6\end{bmatrix} -
\begin{bmatrix}\lambda&0\\0&\lambda\end{bmatrix}\right)\mathbf{x} &= \mathbf{0} \\
\begin{bmatrix}2 - \lambda&3\\3&-6-\lambda\end{bmatrix}\mathbf{x} &= \begin{bmatrix}0\\0\end{bmatrix}
\end{align}
$$

$$
\begin{align}
\det{(\begin{bmatrix}2 - \lambda&3\\3&-6-\lambda\end{bmatrix})} &= 0 \\
\left(2 - \lambda\right)\left(-6 - \lambda\right) - 9 &= 0 \\
-12 - 2\lambda + 6\lambda + \lambda^{2} - 9 &= 0 \\
\lambda^{2} + 4\lambda - 21 &= 0
\end{align}
$$

$$
\begin{align}
\left(\lambda + 7\right)\left(\lambda - 3\right) &= 0
\end{align}
$$

$\therefore \lambda = -7$ or $\lambda = 3$ which are the two eigenvalues of $\mathbf{A}$.

In [22]:
A = sym.Matrix([[2, 3],
                [3, -6]])
A

Matrix([
[2,  3],
[3, -6]])

In [23]:
test = A.charpoly()
test

PurePoly(lambda**2 + 4*lambda - 21, lambda, domain='ZZ')

In [24]:
sym.solve(test.as_expr())

[-7, 3]

In [25]:
A = sym.Matrix([[5, 2, 0],
                [2, 5, 0],
                [-3, 4, 6]])
A

Matrix([
[ 5, 2, 0],
[ 2, 5, 0],
[-3, 4, 6]])

In [26]:
A.eigenvects()

[(3,
  1,
  [Matrix([
   [ 3/7],
   [-3/7],
   [   1]])]),
 (6,
  1,
  [Matrix([
   [0],
   [0],
   [1]])]),
 (7,
  1,
  [Matrix([
   [1],
   [1],
   [1]])])]